-- CreateTable
CREATE TABLE "User" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idvk" INTEGER NOT NULL,
    "name" TEXT NOT NULL DEFAULT 'zero',
    "lvl" INTEGER NOT NULL DEFAULT 1,
    "hp" INTEGER NOT NULL DEFAULT 2,
    "atk" INTEGER NOT NULL DEFAULT 1,
    "mana" INTEGER NOT NULL DEFAULT 0,
    "point" INTEGER NOT NULL DEFAULT 2,
    "crdate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
